[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_badge_system = "ExxobJmjz8DuRNYgd5sq1jZzh5AuvmgmAd1MPv5sp2i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
